version: '3.8'
services:
  # Redis Stack Service
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack-service
    hostname: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"
  # Redis Splunk Ingester Service
  backend:
    image: redis-splunk-ingester:latest
    container_name: ingester-service
    depends_on:
      - redis
    links:
      - "redis:redis"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MOVIE_INSERT_ON_STARTUP=true
      - MOVIE_DATA_DIR=./
    ports:
      - "8686:8686"
    stdin_open: true
    tty: true
networks:
  default:
    name: redis-splunk-network